<a href="https://colab.research.google.com/github/Fasiloc/Machine_Learning_learn-repo/blob/main/Classes/Day_24_pg_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

In [ ]:
df = pd.read_csv('Cancer.csv')

In [ ]:
df

           id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0      842302         M  ...                  0.11890          NaN
1      842517         M  ...                  0.08902          NaN
2    84300903         M  ...                  0.08758          NaN
3    84348301         M  ...                  0.17300          NaN
4    84358402         M  ...                  0.07678          NaN
..        ...       ...  ...                      ...          ...
564    926424         M  ...                  0.07115          NaN
565    926682         M  ...                  0.06637          NaN
566    926954         M  ...                  0.07820          NaN
567    927241         M  ...                  0.12400          NaN
568     92751         B  ...                  0.07039          NaN

[569 rows x 33 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    object
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
 32  Unnamed: 32              0 non-null      float64
dtypes: float64(31), int64(1), object(1)
memory usage: 146.8+ KB

In [ ]:
df = df.drop('Unnamed: 32',axis=1)

In [ ]:
df = df.drop('id',axis=1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   diagnosis                569 non-null    object
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  569 non-null    float64
 15  smoothness_se            569 non-null    float64
 16  compactness_se           569 non-null    float64
 17  concavity_se             569 non-null    float64
 18  concave points_se        569 non-null    float64
 19  symmetry_se              569 non-null    float64
 20  fractal_dimension_se     569 non-null    float64
 21  radius_worst             569 non-null    float64
 22  texture_worst            569 non-null    float64
 23  perimeter_worst          569 non-null    float64
 24  area_worst               569 non-null    float64
 25  smoothness_worst         569 non-null    float64
 26  compactness_worst        569 non-null    float64
 27  concavity_worst          569 non-null    float64
 28  concave points_worst     569 non-null    float64
 29  symmetry_worst           569 non-null    float64
 30  fractal_dimension_worst  569 non-null    float64
dtypes: float64(30), object(1)
memory usage: 137.9+ KB

In [ ]:
df['diagnosis'].value_counts()

B    357
M    212
Name: diagnosis, dtype: int64

In [ ]:
x = df.drop('diagnosis',axis=1)
y = df['diagnosis']

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [ ]:
sc = StandardScaler()

scaler = sc.fit(x_train)
x_train_scaled = scaler.transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [ ]:
mlp_clf = MLPClassifier(hidden_layer_sizes=(50,30),
                        max_iter=300,activation='relu',
                        verbose=True,
                        solver='adam')

mlp_clf.fit(x_train_scaled,y_train)

Iteration 1, loss = 0.71346485
Iteration 2, loss = 0.63181916
Iteration 3, loss = 0.56064715
Iteration 4, loss = 0.49830771
Iteration 5, loss = 0.44457533
Iteration 6, loss = 0.39811037
Iteration 7, loss = 0.35701828
Iteration 8, loss = 0.32025412
Iteration 9, loss = 0.28742333
Iteration 10, loss = 0.25851538
Iteration 11, loss = 0.23362609
Iteration 12, loss = 0.21173172
Iteration 13, loss = 0.19278542
Iteration 14, loss = 0.17659690
Iteration 15, loss = 0.16215215
Iteration 16, loss = 0.14980344
Iteration 17, loss = 0.13916141
Iteration 18, loss = 0.12946609
Iteration 19, loss = 0.12136355
Iteration 20, loss = 0.11397109
Iteration 21, loss = 0.10768683
Iteration 22, loss = 0.10187494
Iteration 23, loss = 0.09692184
Iteration 24, loss = 0.09227341
Iteration 25, loss = 0.08807999
Iteration 26, loss = 0.08432933
Iteration 27, loss = 0.08094621
Iteration 28, loss = 0.07775788
Iteration 29, loss = 0.07483279
Iteration 30, loss = 0.07214879
Iteration 31, loss = 0.06965297
Iteration 32, loss = 0.06744056
Iteration 33, loss = 0.06540025
Iteration 34, loss = 0.06328059
Iteration 35, loss = 0.06156117
Iteration 36, loss = 0.05980185
Iteration 37, loss = 0.05802823
Iteration 38, loss = 0.05652970
Iteration 39, loss = 0.05485591
Iteration 40, loss = 0.05342714
Iteration 41, loss = 0.05210770
Iteration 42, loss = 0.05084457
Iteration 43, loss = 0.04956751
Iteration 44, loss = 0.04842262
Iteration 45, loss = 0.04746869
Iteration 46, loss = 0.04631729
Iteration 47, loss = 0.04527071
Iteration 48, loss = 0.04434188
Iteration 49, loss = 0.04349989
Iteration 50, loss = 0.04269037
Iteration 51, loss = 0.04189094
Iteration 52, loss = 0.04119438
Iteration 53, loss = 0.04032810
Iteration 54, loss = 0.03959581
Iteration 55, loss = 0.03890889
Iteration 56, loss = 0.03806433
Iteration 57, loss = 0.03745430
Iteration 58, loss = 0.03690455
Iteration 59, loss = 0.03629025
Iteration 60, loss = 0.03572992
Iteration 61, loss = 0.03510595
Iteration 62, loss = 0.03449649
Iteration 63, loss = 0.03399245
Iteration 64, loss = 0.03341827
Iteration 65, loss = 0.03292545
Iteration 66, loss = 0.03244721
Iteration 67, loss = 0.03188404
Iteration 68, loss = 0.03143707
Iteration 69, loss = 0.03098242
Iteration 70, loss = 0.03056731
Iteration 71, loss = 0.03012027
Iteration 72, loss = 0.02957706
Iteration 73, loss = 0.02909842
Iteration 74, loss = 0.02855078
Iteration 75, loss = 0.02818343
Iteration 76, loss = 0.02772458
Iteration 77, loss = 0.02728128
Iteration 78, loss = 0.02690299
Iteration 79, loss = 0.02649195
Iteration 80, loss = 0.02613839
Iteration 81, loss = 0.02582156
Iteration 82, loss = 0.02541225
Iteration 83, loss = 0.02500359
Iteration 84, loss = 0.02464292
Iteration 85, loss = 0.02433321
Iteration 86, loss = 0.02400520
Iteration 87, loss = 0.02366199
Iteration 88, loss = 0.02329648
Iteration 89, loss = 0.02301783
Iteration 90, loss = 0.02265227
Iteration 91, loss = 0.02239143
Iteration 92, loss = 0.02189778
Iteration 93, loss = 0.02156300
Iteration 94, loss = 0.02113290
Iteration 95, loss = 0.02084494
Iteration 96, loss = 0.02056407
Iteration 97, loss = 0.02019690
Iteration 98, loss = 0.02004380
Iteration 99, loss = 0.01963437
Iteration 100, loss = 0.01919917
Iteration 101, loss = 0.01904202
Iteration 102, loss = 0.01859323
Iteration 103, loss = 0.01824654
Iteration 104, loss = 0.01797298
Iteration 105, loss = 0.01761445
Iteration 106, loss = 0.01722902
Iteration 107, loss = 0.01710512
Iteration 108, loss = 0.01673712
Iteration 109, loss = 0.01643358
Iteration 110, loss = 0.01617264
Iteration 111, loss = 0.01592860
Iteration 112, loss = 0.01567325
Iteration 113, loss = 0.01546119
Iteration 114, loss = 0.01522371
Iteration 115, loss = 0.01506786
Iteration 116, loss = 0.01487161
Iteration 117, loss = 0.01459166
Iteration 118, loss = 0.01438391
Iteration 119, loss = 0.01416945
Iteration 120, loss = 0.01398720
Iteration 121, loss = 0.01375720
Iteration 122, loss = 0.01359540
Iteration 123, loss = 0.01339177
Iteration 124, loss = 0.01323661
Iteration 125, loss = 0.01306499
Iteration 126, loss = 0.01283150
Iteration 127, loss = 0.01264997
Iteration 128, loss = 0.01243499
Iteration 129, loss = 0.01221085
Iteration 130, loss = 0.01202473
Iteration 131, loss = 0.01190120
Iteration 132, loss = 0.01177795
Iteration 133, loss = 0.01168733
Iteration 134, loss = 0.01147932
Iteration 135, loss = 0.01130223
Iteration 136, loss = 0.01107892
Iteration 137, loss = 0.01094706
Iteration 138, loss = 0.01073024
Iteration 139, loss = 0.01052014
Iteration 140, loss = 0.01033719
Iteration 141, loss = 0.01015102
Iteration 142, loss = 0.01000116
Iteration 143, loss = 0.00991322
Iteration 144, loss = 0.00972689
Iteration 145, loss = 0.00954835
Iteration 146, loss = 0.00934260
Iteration 147, loss = 0.00917462
Iteration 148, loss = 0.00906641
Iteration 149, loss = 0.00886651
Iteration 150, loss = 0.00873343
Iteration 151, loss = 0.00854054
Iteration 152, loss = 0.00843317
Iteration 153, loss = 0.00827254
Iteration 154, loss = 0.00813899
Iteration 155, loss = 0.00803521
Iteration 156, loss = 0.00794230
Iteration 157, loss = 0.00778566
Iteration 158, loss = 0.00768103
Iteration 159, loss = 0.00752252
Iteration 160, loss = 0.00740224
Iteration 161, loss = 0.00729902
Iteration 162, loss = 0.00720348
Iteration 163, loss = 0.00709218
Iteration 164, loss = 0.00700587
Iteration 165, loss = 0.00688872
Iteration 166, loss = 0.00676372
Iteration 167, loss = 0.00665965
Iteration 168, loss = 0.00657170
Iteration 169, loss = 0.00647361
Iteration 170, loss = 0.00639631
Iteration 171, loss = 0.00630611
Iteration 172, loss = 0.00621236
Iteration 173, loss = 0.00611681
Iteration 174, loss = 0.00605033
Iteration 175, loss = 0.00595899
Iteration 176, loss = 0.00586489
Iteration 177, loss = 0.00577079
Iteration 178, loss = 0.00570711
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

MLPClassifier(hidden_layer_sizes=(50, 30), max_iter=300, verbose=True)

In [ ]:
y_pred = mlp_clf.predict(x_test_scaled)
print('Accuracy :',accuracy_score(y_test,y_pred))

Accuracy : 0.9649122807017544